// <auto-generated />
namespace WebAPI.Dll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _030720191 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_030720191));
        
        string IMigrationMetadata.Id
        {
            get { return "201907030045411_03-07-2019-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
